version: "3.9"

services:
  flask-app:
    build:
      context: ./local_app
    ports:
      - "5000:5000"
    volumes:
      - ./local_app:/app  # Mount the app directory from the host to the container
    restart: always
